apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    name: red-container
  initContainers:
  - name: red-initcontainer
    image: busybox
    command: ['sh', '-c', 'sleep 20']
  